version: 2.1

orbs:

  build:
    jobs:

      run-build:
        parameters:
          image-tag:
            description: The .NET Core SDK image tag to use.
            type: string
          build-config:
            description: The build configuration, either Debug or Release.
            type: string
          framework:
            description: The .NET Core App framework target.
            type: string
        executor:
          name: dotnet-build-executor
          tag: << parameters.image-tag >>
        steps:
          - checkout
          - run:
              name: Restore
              command: dotnet restore
          - run:
              name: Build
              command: dotnet build --no-restore -f << parameters.framework >> -c << parameters.build-config >> ./test/Tesla.NET.Tests/Tesla.NET.Tests.csproj
          - run:
              name: Test
              command: dotnet test --no-restore --no-build -f << parameters.framework >> -c << parameters.build-config >> ./test/Tesla.NET.Tests/Tesla.NET.Tests.csproj /p:CollectCoverage=true
          - store_artifacts:
              path: ./test/Tesla.NET.Tests/coverage.json
              destination: coverage.json

    executors:

      dotnet-build-executor:
        parameters:
          tag:
            description: The .NET Core SDK image tag to use.
            type: string
        docker:
          - image: mcr.microsoft.com/dotnet/core/sdk:<<parameters.tag>>

workflows:

  "Build All Frameworks":
    jobs:
      - build/run-build:
          name: 2.1 Debug Build
          image-tag: "2.1"
          build-config: Debug
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.1 Alpine Debug Build
          image-tag: "2.1-alpine"
          build-config: Debug
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.1 Release Build
          image-tag: "2.1"
          build-config: Release
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.1 Alpine Release Build
          image-tag: "2.1-alpine"
          build-config: Release
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.2 Debug Build
          image-tag: "2.2"
          build-config: Debug
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.2 Alpine Debug Build
          image-tag: "2.2-alpine"
          build-config: Debug
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.2 Release Build
          image-tag: "2.2"
          build-config: Release
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.2 Alpine Release Build
          image-tag: "2.2-alpine"
          build-config: Release
          framework: netcoreapp2.1
